# -*- coding: utf-8 -*-
# REPLENV: /home/fdo/pyenv/qgis
"""
/***************************************************************************
 fire2amClass
                                 A QGIS plugin
 Simulate a forest fires under different weather and fire model scenarios
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-07
        git sha              : $Format:%H$ (git show -s --format=%H)
        copyright            : (C) 2023 by fdobadvel (gui) & fire2a team
        email                : fire2a@fire2a.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

TODO:
    run_normal with empty weather folder stop!

1. fire2amClass __init__ : registers launch buttons on toolbar

2. fire2amClass.run_Dialog : slot when dialog button is pressed

2.1 if first_start_dialog
    fire2amClassDialog() : build class
    first_start_setup() :
        setup layerComboxes filter
        regex match layerComboxes with current available layers
        check if weather file & folder exists in current project directory
    connect_slots() : connect all ui buttons with their slot_callbacks

2.2 else listen to ui signals

3. run_normal : executes the simulation
        dlg.updateState() : get all ui parameters updated to dlg.state dictionary
        updateProject() :
            get global params (fuel layer W, H, extent, crs)
            self.project : TODO discard ? be able to run without a project saved
n--         get datetime.now() TODO discard?
        checkMap() : check raster sizes & crs match
        makeArgs() : argparse
            4. if argparse
                infolder = Instance_nowString
                proc dir&executable
        writeInstance()
        externalProcess_start()

4. externalProcess_finished
        proc = None
        after()
5. after


"""
import os.path
import re
import stat
from datetime import datetime, timedelta
from glob import glob
from os import sep
from pathlib import Path
from platform import system as plt_sys
from shutil import copy

import numpy as np
from pandas import DataFrame
from qgis.core import (Qgis, QgsApplication, QgsCoordinateReferenceSystem,
                       QgsMapLayerProxyModel, QgsMapLayerType, QgsMessageLog,
                       QgsProject, QgsTask, QgsWkbTypes)
from qgis.PyQt.Qt import Qt
from qgis.PyQt.QtCore import (QCoreApplication, QProcess, QSettings, QTimer,
                              QTranslator)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QCheckBox, QDoubleSpinBox, QSpinBox

from . import fire2a_checks
from .fire2am_argparse import fire2amClassDialogArgparse
from .fire2am_bkgdTask import (after_asciiDir, after_betweenness_centrality,
                               after_downstream_protection_value,
                               after_ForestGrid, after_logFile,
                               check_weather_folder_bkgd)
from .fire2am_CONSTANTS import (GRID_EMPTY_DF, GRID_NAMES, STATS_BASE_DF,
                                STATS_BASE_NAMES, STATS_DESCRIBE_NAMES, TAG)
from .fire2am_dialog import fire2amClassDialog
from .fire2am_utils import check as fdoCheck
from .fire2am_utils import get_params, nlog
# Initialize Qt resources from file resources.py
from .img.resources import *  # pylint: disable=wildcard-import, unused-wildcard-import
from .ParseInputs2 import Parser2
from .qgis_utils import (check_gdal_driver_name, checkLayerPoints,
                         matchPoints2Raster)

# For debugging
# import pdb
# from qgis.PyQt.QtCore import pyqtRemoveInputHook
#  These lines allow you to set a breakpoint in the app
# pyqtRemoveInputHook()
# pdb.set_trace()
#  This line enters into interactive
# (Pdb) !import code; code.interact(local=dict(globals(), **locals()))
#  ?
# import warnings
# warnings.filterwarnings("ignore",message='Warning: QCoreApplication::exec: The event loop is already running')

nlog = nlog(QgsMessageLog())


class fire2amClass:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(self.plugin_dir, "i18n", f"fire2amClass_{locale}.qm")

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&Fire Simulator Analytics Management")

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start_dialog = None
        self.first_start_argparse = None

        # argparse
        self.default_args, self.parser, self.groups = get_params(Parser2)
        self.gen_cmd = ""
        self.args = {}

        # global
        self.project = None
        self.crs = None
        self.extent = None
        self.W = None
        self.H = None

        # QProcess
        self.proc_dir = str(Path(self.plugin_dir, "C2FSB"))
        self.proc_exe = "python3 main.py"
        self.simulation_process = None
        self.proc = None
        self.name_state = {
            QProcess.ProcessState.NotRunning: "Not running",
            QProcess.ProcessState.Starting: "Starting",
            QProcess.ProcessState.Running: "Running",
        }
        # QgsTask
        self.task = {}
        self.taskManager = QgsApplication.taskManager()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.
        We implement this ourselves since we do not inherit QObject.
        :param message: String for translation.
        :type message: str, QString
        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("fire2amClass", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ":/plugins/fire2am/img/icon.png"
        self.add_action(
            icon_path,
            text=self.tr(f"{TAG}: setup and run a forest fire simulation..."),
            callback=self.run_Dialog,
            parent=self.iface.mainWindow(),
        )
        # dock start
        self.add_action(
            icon_path=":/plugins/fire2am/img/icon_dev.png",
            text=self.tr(f"{TAG}: all options (very experimental)"),
            callback=self.run_Argparse,
            parent=self.iface.mainWindow(),
            add_to_toolbar=True,
        )
        # dock end

        # will be set False in run()
        self.first_start_dialog = True
        self.first_start_argparse = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&Fire Simulator Analytics Management"), action)
            self.iface.removeToolBarIcon(action)

    def check_binary(self):
        """check if binary exists"""
        ext = ""
        if plt_sys() == "Windows":
            ext = ".exe"
        afile = Path(self.plugin_dir, "C2FSB", "Cell2FireC", "Cell2Fire" + ext)
        if not afile.is_file():
            self.iface.messageBar().pushMessage(
                f"{TAG}:", f"Cell2Fire{ext} binary not found! will not simulate", level=2, duration=0
            )
            self.dlg.msgBar.pushMessage(
                f"{TAG}:", f"Cell2Fire{ext} binary not found! will not simulate", level=2, duration=0
            )
            self.dlg.plainTextEdit.appendPlainText(
                f"Cell2Fire{ext} binary not found! {TAG} will not simulate until the file placed at {afile}"
            )
            self.dlg.pushButton_run.setEnabled(False)
            self.dlg.pushButton_run_dev.setEnabled(False)
            return
        if plt_sys() != "Windows":
            os.chmod(
                afile,
                stat.S_IRUSR
                | stat.S_IWUSR
                | stat.S_IXUSR
                | stat.S_IRGRP
                | stat.S_IWGRP
                | stat.S_IXGRP
                | stat.S_IROTH
                | stat.S_IWOTH
                | stat.S_IXOTH,
            )

    def run_Argparse(self):
        """Argparse dialog run method that performs all the real work"""
        if self.first_start_argparse is True:
            self.first_start_argparse = False
            self.argdlg = fire2amClassDialogArgparse()
            nlog("created", title="argdlg", text="run_Argparse")
        nlog("opened", title="argdlg", text="run_Argparse")
        self.argdlg.show()
        result = self.argdlg.exec_()
        nlog("closed", title="argdlg", text="run_Argparse", result=result)

    def showPlot(self, index):
        nlog(title="plots", text=f"Showing plot index:{index}")
        self.dlg.plt.show(index)

    def run_Dialog(self):
        """Run method that performs all the real work"""
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start_dialog is True:
            self.first_start_dialog = False
            self.dlg = fire2amClassDialog()
            nlog.set_qgsMessageBar(self.dlg.msgBar)
            self.dlg.set_nlog(nlog)
            self.dlg.slot_windRandomize()
            self.dlg.tabWidget.setCurrentIndex(0)
            self.first_start_setup()
            self.simulation_process = C2FSB(
                proc_dir=self.proc_dir, on_finished=self.after, plainTextEdit=self.dlg.plainTextEdit
            )
            self.check_binary()
            self.connect_slots()
            self.project = QgsProject().instance()
            nlog("created", title="main dialog", text="run_Dialog")
        # removed check if they are layers present
        # if QgsProject.instance().mapLayers() == {}:
        #     self.iface.messageBar().pushCritical(TAG+': No layers found', 'Open a project with layers and try again')
        #     nlog(text='Open a project with layers and restore defaults', title='No layers found', level=2)
        #     return
        #  if project changed
        if self.project != QgsProject().instance():
            old = self.project
            self.project = QgsProject().instance()
            nlog(
                title="Project Changed!",
                text="It's easier if the project is saved in the same folder as the rasters",
                level=2,
                old_path=old.absoluteFilePath(),
                old_name=old.baseName(),
                new_path=self.project.absoluteFilePath(),
                new_name=self.project.baseName(),
            )
        # if project not saved
        if QgsProject().instance().absolutePath() == "":
            self.iface.messageBar().pushMessage(
                TAG,
                "Save the project in the same folder as the rasters. Raising the save dialog...",
                level=2,
                duration=2,
            )
            QTimer().singleShot(2222, lambda: self.iface.actionSaveProject().trigger())
            return
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        nlog(title="main dialog", text="ran", result=result)

    def first_start_setup(self):
        """layers default names"""
        # layer only accept these types (not working in QtDesigner)
        self.dlg.layerComboBox_fuels.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg.layerComboBox_elevation.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg.layerComboBox_cbd.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg.layerComboBox_cbh.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg.layerComboBox_ccf.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg.layerComboBox_pv.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg.layerComboBox_ignitionProbMap.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg.layerComboBox_ignitionPoints.setFilters(QgsMapLayerProxyModel.PointLayer)
        # TODO check for each layerComboBox set if any layer_name matchs its regex else set to None.
        # extras/better_layerComboBox_matching.py
        layers_byName = {lyr.name(): lyr for lyr in QgsProject.instance().mapLayers().values()}
        for lname, layer in layers_byName.items():
            if re.match("model.*asc", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_fuels.setLayer(layer)
                layer.loadNamedStyle(os.path.join(self.plugin_dir, "img" + sep + "fuelsSB_layerStyle.qml"))
                layer.triggerRepaint()
            elif re.match("mdt.*asc", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_elevation.setLayer(layer)
            elif re.match("cbh", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_cbh.setLayer(layer)
            elif re.match("cbd", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_cbd.setLayer(layer)
            elif re.match("ccf", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_ccf.setLayer(layer)
            elif re.match("^py", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_ignitionProbMap.setLayer(layer)
                self.dlg.radioButton_ignitionProbMap.setChecked(True)
            elif re.match("[Ee]levation", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_elevation.setLayer(layer)
            elif re.match("[Ff]uel", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_fuels.setLayer(layer)
            elif re.match("[Ii]gnition.*[Pp]rob", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_ignitionProbMap.setLayer(layer)
            elif (
                re.match("[Ii]gnition.*[Pp]oint", lname)
                and layer.type() == QgsMapLayerType.VectorLayer
                and layer.wkbType() == QgsWkbTypes.Point
            ):
                self.dlg.layerComboBox_ignitionPoints.setLayer(layer)
            elif re.match(".*[Vv]alue.*", lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_pv.setLayer(layer)
        """ weather file"""
        if apath := QgsProject.instance().absolutePath():
            wfile = Path(apath, "Weather.csv")
            if wfile.is_file():
                if fire2a_checks.weather_file(wfile):
                    self.dlg.fileWidget_weatherFile.setFilePath(str(wfile))
                    self.dlg.radioButton_weatherFile.setChecked(True)
            """ weather folder """
            wfolder = Path(apath, "Weathers")
            if wfolder.is_dir():
                name = "check_weather_folder_bkgd"
                self.task[name] = check_weather_folder_bkgd(name, self.dlg, wfolder)
                self.taskManager.addTask(self.task[name])

    def connect_slots(self):
        """main"""
        # self.dlg.tabWidget.currentChanged.connect(self.slot_tabWidget_currentChanged)
        self.dlg.pushButton_restoreDefaults.pressed.connect(self.slot_restoreDefaults)
        self.dlg.pushButton_run.pressed.connect(self.run_normal)
        """ tab landscape """
        self.dlg.layerComboBox_fuels.layerChanged.connect(self.slot_trySelectFuelRaster)
        self.dlg.layerComboBox_elevation.layerChanged.connect(self.slot_trySelectRaster)
        self.dlg.layerComboBox_cbh.layerChanged.connect(self.slot_trySelectRaster)
        self.dlg.layerComboBox_cbd.layerChanged.connect(self.slot_trySelectRaster)
        self.dlg.layerComboBox_ccf.layerChanged.connect(self.slot_trySelectRaster)
        self.dlg.layerComboBox_pv.layerChanged.connect(self.slot_trySelectRaster)
        """ tab ignitions """
        self.dlg.layerComboBox_ignitionPoints.layerChanged.connect(self.slot_layerComboBox_ignitionPoints_layerChanged)
        self.dlg.layerComboBox_ignitionProbMap.layerChanged.connect(self.slot_trySelectRaster)
        self.dlg.radioButton_ignitionPoints.clicked.connect(self.slot_radioButton_ignitionPoints_clicked)
        self.dlg.radioButton_ignitionProbMap.clicked.connect(self.slot_radioButton_ignitionProbMap_clicked)
        """ tab weather """
        self.dlg.fileWidget_weatherFile.fileChanged.connect(self.slot_fileWidget_weatherFile_fileChanged)
        self.dlg.fileWidget_weatherFolder.fileChanged.connect(self.slot_fileWidget_weatherFolder_fileChanged)
        self.dlg.radioButton_weatherFile.clicked.connect(self.slot_radioButton_weatherFile_clicked)
        self.dlg.radioButton_weatherFolder.clicked.connect(self.slot_radioButton_weatherFolder_clicked)
        """ tab run """
        self.dlg.pushButton_run_dev.pressed.connect(self.run_dev)
        self.dlg.pushButton_kill.pressed.connect(self.simulation_process.kill)
        self.dlg.pushButton_terminate.pressed.connect(self.simulation_process.terminate)
        self.dlg.pushButton_run_after.pressed.connect(self.slot_run_after)
        """ tab tables """
        """ tab graphs """
        self.dlg.comboBox_plot.currentIndexChanged.connect(lambda index: self.dlg.plt.show(index))

    def slot_radioButton_ignitionProbMap_clicked(self):
        """When the raidioButton is selected, check if there's a layer Widget
        else change to ignition random
        """
        if not self.dlg.layerComboBox_ignitionProbMap.currentLayer():
            self.dlg.radioButton_ignitionRandom.setChecked(True)
            nlog(
                text="Select a layer before selecting!",
                title="No ProbabilityMap!",
                level=2,
                to_bar=True,
                duration=2,
            )

    def slot_radioButton_ignitionPoints_clicked(self):
        """When the raidioButton is selected, check if there's a layer Widget
        else change to ignition random
        """
        if not self.dlg.layerComboBox_ignitionPoints.currentLayer():
            self.dlg.radioButton_ignitionRandom.setChecked(True)
            nlog(
                text="Select a layer before selecting!",
                title="No Ignition Layer!",
                level=2,
                to_bar=True,
                duration=2,
            )

    def slot_radioButton_weatherFile_clicked(self):
        """When the raidioButton is selected, check if there's a file on the fileWidget
        else change to weatherConstant
        """
        if not Path(self.dlg.fileWidget_weatherFile.filePath()).is_file():
            self.dlg.radioButton_weatherConstant.setChecked(True)
            nlog(
                text="Select a file first before selecting!",
                title="No Weather File!",
                level=2,
                to_bar=True,
                duration=2,
            )

    def slot_radioButton_weatherFolder_clicked(self):
        """When the raidioButton is selected, check if there's a directory on the fileWidget
        else change to weatherConstant
        """
        if (
            not Path(self.dlg.fileWidget_weatherFolder.filePath()).is_dir()
            or self.dlg.fileWidget_weatherFolder.filePath() == ""
        ):
            self.dlg.radioButton_weatherConstant.setChecked(True)
            nlog(
                text="Select a directory first before selecting!",
                title="No Weather Folder!",
                level=2,
                to_bar=True,
                duration=2,
            )

    def writeInstance(self):
        """write instance (exiting in each point if something fails)
        check args['inFolder'] is new
        copy fuel definition csv
        copy fuel raster file
        if exists, copy elevation, cbh, cbd, ccf layers file
        weather choosen:
            file : copy file
            folder: copy folder
            constant: make csv
        ignition choosen:
            point : make ignitions.csv
            probability map: copy file
        """
        # inFolder
        if os.path.isdir(self.args["InFolder"]):
            nlog(
                text=f"directory named {self.args['InFolder']}, stopping!",
                title="Already Exists!",
                level=2,
                to_bar=True,
            )
            return
        os.mkdir(self.args["InFolder"])
        nlog(
            title="writeInstance",
            text="Created directory",
            InFolder=self.args["InFolder"],
            level=0,
        )
        # fuel definition
        fuel_file = "spain_lookup_table.csv"
        copy(os.path.join(self.plugin_dir, fuel_file), self.args["InFolder"])
        # fuels layer
        copy(self.dlg.state["layerComboBox_fuels"].publicSource(), os.path.join(self.args["InFolder"], "fuels.asc"))
        nlog(
            title="writeInstance",
            text="fuels definition copied",
            fuel_file=fuel_file,
            level=0,
        )
        # layers elevation cbh cbd ccf pv
        for name in ["elevation", "cbh", "cbd", "ccf", "pv"]:
            layer = self.dlg.state["layerComboBox_" + name]
            if layer:
                copy(
                    self.dlg.state["layerComboBox_" + name].publicSource(),
                    os.path.join(self.args["InFolder"], name + ".asc"),
                )
                nlog(
                    title="writeInstance",
                    text="layer copied",
                    name=name,
                    level=0,
                )
        # weather
        # weather constant : read dial and slider to generate Weather.csv
        if self.dlg.state["radioButton_weatherConstant"]:
            nrows = self.dlg.state["spinBox_windConstLen"]
            iname = QgsProject().instance().baseName()
            if iname == "":
                iname = "Jaime"
            Instance = [iname] * nrows
            FireScenario = [2] * nrows
            dt = [(self.now + timedelta(hours=i)).isoformat(timespec="minutes") for i in range(nrows)]
            WD = [self.dlg.state["spinBox_windDirection"]] * nrows
            WS = [self.dlg.state["spinBox_windSpeed"]] * nrows
            df = DataFrame(
                np.vstack((Instance, dt, WD, WS, FireScenario)).T,
                columns=["Instance", "datetime", "WD", "WS", "FireScenario"],
            )
            df.to_csv(os.path.join(self.args["InFolder"], "Weather.csv"), header=True, index=False)
            nlog(
                title="writeInstance",
                text="generated weather",
                wind_speed=WS,
                level=0,
            )
            nlog(
                title="writeInstance",
                text="generated weather",
                wind_direction=WD,
                level=0,
            )
        # weather file
        elif self.dlg.state["radioButton_weatherFile"]:
            copy(self.dlg.state["fileWidget_weatherFile"], os.path.join(self.args["InFolder"], "Weather.csv"))
            nlog(
                title="writeInstance",
                text="weather copied",
                file=self.dlg.state["fileWidget_weatherFile"],
                level=0,
            )
        # weather folder
        elif self.dlg.state["radioButton_weatherFolder"]:
            dst = os.path.join(self.args["InFolder"], "Weathers")
            os.mkdir(dst)
            for filename in glob(self.dlg.state["fileWidget_weatherFolder"] + sep + "Weather[0-9]*.csv"):
                copy(filename, dst)
            nlog(
                title="writeInstance",
                text="weather copied",
                folder=self.dlg.state["fileWidget_weatherFolder"],
                level=0,
            )
        # ignition
        # ignition point : match layer points to raster layer coords, write Ignitions.csv with cell id
        if self.dlg.state["radioButton_ignitionPoints"]:
            points = self.dlg.state["layerComboBox_ignitionPoints"]
            raster = self.dlg.state["layerComboBox_fuels"]
            cellIds, _, _ = matchPoints2Raster(raster, points)
            Ncell = [c + 1 for c in cellIds]
            if not Ncell:
                nlog(
                    text=f"for {points.name()} into fuel raster (CRS match?)",
                    title="Fatal: No matching point",
                    level=2,
                    to_bar=True,
                )
                return
            # TODO make the simulator accept more than 1 point
            # data = { 'Year':None, 'Ncell': Ncell }
            data = {"Year": 1, "Ncell": [Ncell[0]]}
            df = DataFrame.from_dict(data)
            # df.fillna(1, inplace=True)
            df.to_csv(os.path.join(self.args["InFolder"], "Ignitions.csv"), header=True, index=False)
            nlog(
                title="writeInstance",
                text="Ignition point",
                cell=Ncell[0],
                level=0,
            )
        # ignition prob map
        elif self.dlg.state["radioButton_ignitionProbMap"]:
            copy(
                self.dlg.state["layerComboBox_ignitionProbMap"].publicSource(),
                os.path.join(self.args["InFolder"], "py.asc"),
            )
            nlog(
                title="writeInstance",
                text="ignitionProbMap copied",
                layer=self.dlg.state["layerComboBox_ignitionProbMap"].name(),
                level=0,
            )
        nlog(
            title="writeInstance",
            text="finished ok!",
            level=3,
            to_bar=True,
        )

    def slot_trySelectFuelRaster(self, layer):
        try:
            if not layer:
                return
            layer_name = layer.name()
            ret, val = check_gdal_driver_name(layer, driver_name="AAIGrid")
            if not ret:
                nlog(
                    text=f"{layer_name} has incompatible {val} format! try gdal_translate -of AAIGrid",
                    title="Not AAIGrid fuel layer!",
                    level=1,
                    to_bar=True,
                )
                return
            if layer.crs().isValid():
                self.crs = layer.crs
                self.extent = layer.extent
            else:
                nlog(
                    text=f'Selected fuel layer "{layer_name}" CRS not set!',
                    title="Fuel CRS!",
                    level=1,
                    to_bar=True,
                )
                if QgsProject().instance().crs().isValid():
                    self.crs = QgsProject().instance().crs
                    layer.setCrs(self.crs())
                    self.extent = layer.extent
                    nlog(
                        text="Defaulting to project CRS!",
                        title="Fuel CRS set from project!",
                        level=1,
                        to_bar=True,
                    )
                else:
                    # Note maybe the program should never reach here!
                    nlog(
                        text="Neither the project nor the Fuel layer have a valid CRS!",
                        title="Must set CRSs!",
                        level=1,
                        to_bar=True,
                    )
                    self.crs = None
            self.W = layer.width()
            self.H = layer.height()
            layer.loadNamedStyle(os.path.join(self.plugin_dir, "img" + sep + "fuelsSB_layerStyle.qml"))
            layer.triggerRepaint()
            nlog(
                title="fuel combobox",
                text="selected",
                layer=layer_name,
                level=3,
                W=self.W,
                H=self.H,
                crs=self.crs().description(),
                extent=self.extent().asWktCoordinates(),
            )
        except Exception as e:
            nlog(text=f'"{e}" problem selecting "{layer_name()}"', title="Fuel Exception!", level=2, to_bar=True)

    def slot_trySelectRaster(self, layer):
        try:
            if not layer:
                return
            layer_name = layer.name()
            name = self.dlg.sender().objectName()
            ret, val = check_gdal_driver_name(layer, driver_name="AAIGrid")
            if not ret:
                nlog(
                    text=f"{layer_name} has incompatible {val} format! try gdal_translate -of AAIGrid",
                    title="Not AAIGrid layer!",
                    level=1,
                    to_bar=True,
                )
                return
            nlog(
                text=f"{name} comboBox selected {layer_name}",
                title="Is AAIGrid raster!",
                level=3,
                to_bar=True,
            )
        except Exception as e:
            nlog(text=f'"{e}" problem selecting "{layer_name()}"', title="Raster Exception!", level=2, to_bar=True)

    def slot_layerComboBox_ignitionPoints_layerChanged(self, layer):
        def warn_reject(msg, layer_name):
            self.dlg.radioButton_ignitionRandom.setChecked(True)
            nlog(text=f"layer {layer_name}", title=msg, level=1, to_bar=True)

        try:
            if not layer:
                return
            layer_name = layer.name()
            if not layer.type() == QgsMapLayerType.VectorLayer:
                warn_reject("Not vector!", layer_name)
                return
            if not layer.wkbType() == QgsWkbTypes.Point:
                warn_reject("Not with Points!", layer_name)
                return
            pts = [
                f.geometry()
                for f in layer.getFeatures()
                if fdoCheck(f, "geometry") and f.geometry().wkbType() == QgsWkbTypes.Point
            ]
            num_pts = len(pts)
            if num_pts == 0:
                warn_reject("0 points found!", layer_name)
                return
            if num_pts == 1:
                nlog(text=f"from {layer_name} layer", title="Read point!", level=3, to_bar=True)
            elif num_pts > 1:
                nlog(
                    text=f"Only the first one will be used! from {layer_name} layer",
                    title=">1 point!",
                    level=3,
                    to_bar=True,
                )
            self.dlg.radioButton_ignitionPoints.setChecked(True)
        except Exception as e:
            nlog(
                text=f'"{e}" problem selecting "{layer_name}"', title="Ignition Point Exception!", level=2, to_bar=True
            )

    def slot_fileWidget_weatherFolder_fileChanged(self, directory):
        name = "check_weather_folder_bkgd"
        if name in self.task:
            if self.task[name].finished:
                pass
            elif self.task[name].status() not in [QgsTask.Complete, QgsTask.Terminated]:
                nlog(
                    text="Cancel current checking first!",
                    title="Weather Folder busy!",
                    level=1,
                    to_bar=True,
                    duration=2,
                )
                return
        self.task[name] = check_weather_folder_bkgd(name, self.dlg, directory)
        self.taskManager.addTask(self.task[name])

    def slot_fileWidget_weatherFile_fileChanged(self, afile):
        try:
            afile = Path(afile)
            if fire2a_checks.weather_file(afile):
                self.dlg.radioButton_weatherFile.setChecked(True)
                self.dlg.state["radioButton_weatherFile"] = True
                self.dlg.state["fileWidget_weatherFile"] = str(afile)
                nlog(text="looks ok!", title="Weather.csv", level=3, to_bar=True)
                return
            nlog(
                text=f"file {afile} format problem",
                title="Weather.csv",
                level=1,
                to_bar=True,
            )
        except Exception as e:
            nlog(
                text=f'"{e}" problem selecting "{afile}"',
                title="Weather.csv Exception!",
                level=2,
                to_bar=True,
                duration=2,
            )
        self.dlg.fileWidget_weatherFile.blockSignals(True)
        if QgsProject().instance().absolutePath() != "":
            self.dlg.fileWidget_weatherFile.setFilePath(QgsProject().instance().absolutePath())
        self.dlg.radioButton_weatherConstant.setChecked(True)
        self.dlg.fileWidget_weatherFile.blockSignals(False)

    def makeArgs(self):
        """0 empty args
        1 update with dlg values from spinboxes
            delete extra ui spinboxes helpers
        2 update with ui logic
        2a  weathers
        2b  ignitions
        2c  nsims
        3 delete default args
        4 update with argparse dialog
            if opened: with true clicked boxes
            set In|OutFolders = Instance+now
        5 generate command line string
        """
        # 0
        args = {}
        gen_cmd = ""
        # 1
        args.update(
            {
                o.objectName()[o.objectName().index("_") + 1 :]: o.value()
                for o in self.dlg.findChildren((QDoubleSpinBox, QSpinBox), options=Qt.FindChildrenRecursively)
            }
        )
        args.update(
            {
                o.objectName()[o.objectName().index("_") + 1 :]: o.isChecked()
                for o in self.dlg.findChildren(QCheckBox, options=Qt.FindChildrenRecursively)
                if o.isChecked()
            }
        )
        nlog(
            text="step 1",
            title="makeArgs",
            args=args,
        )
        args.pop("windDirection")
        args.pop("windSpeed")
        args.pop("windConstLen")
        # 1 landscape canopy logic
        if any(
            [
                self.dlg.state["layerComboBox_cbd"],
                self.dlg.state["layerComboBox_cbh"],
                self.dlg.state["layerComboBox_ccf"],
            ]
        ):
            args["cros"] = True
        # 2a weather logic
        if self.dlg.state["radioButton_weatherFolder"]:
            args["WeatherOpt"] = "random"
            args["nweathers"] = self.dlg.args["nweathers"]
            # len(list(Path(self.dlg.state['fileWidget_weatherFolder']).glob('Weather[0-9]*.csv')))
        elif self.dlg.state["radioButton_weatherFile"] or self.dlg.state["radioButton_weatherConstant"]:
            args["WeatherOpt"] = "rows"
        # 2b ignition logic
        if self.dlg.state["radioButton_ignitionPoints"]:
            args["ignitions"] = True
        else:
            args.pop("IgRadius")
        # 2c nsims logic
        if args["nsims"] == 1:
            args["grids"] = True
        else:
            args["finalGrid"] = True
        nlog(
            text="step 2",
            title="makeArgs",
            args=args,
        )
        # 2d crow fire logic
        # TODO ? ['OutFl', 'OutIntensity', 'OutRos']
        if "OutCrown" in args or "OutCrownConsumption" in args:
            args["cros"] = True
        # 2e betweenness_centrality
        if self.dlg.state["checkBox_betweennessCentrality"] or self.dlg.state["checkBox_downstreamProtectionValue"]:
            args["OutMessages"] = True
        # 3 discard default value args
        popkeys = []
        for dkey in self.default_args:
            for akey in args:
                if dkey == akey and self.default_args[dkey] == args[akey]:
                    popkeys += [akey]
        for akey in popkeys:
            args.pop(akey)
        nlog(
            text="step 3",
            title="makeArgs",
            args=args,
        )
        # 4 update argparse dialog
        self.now_str = self.now.strftime("%y-%m-%d_%H-%M-%S")
        if self.first_start_argparse:
            """never opened"""
            args["InFolder"] = Path(self.project.absolutePath(), "Instance" + self.now_str)
            args["OutFolder"] = Path(args["InFolder"], "results")
        else:
            """did opened"""
            args.update(self.argdlg.gen_args)
            """ but didnt mention ioFolder """
            if "InFolder" not in self.argdlg.gen_args:
                args["InFolder"] = Path(self.project.absolutePath(), "Instance" + self.now_str)
            else:
                args["InFolder"] = Path(args["InFolder"])
            if "OutFolder" not in self.argdlg.gen_args:
                args["OutFolder"] = Path(args["InFolder"], "results")
            else:
                args["OutFolder"] = Path(args["OutFolder"])
            self.proc_dir = self.argdlg.fileWidget_directory.filePath()
            self.proc_exe = self.argdlg.header
        nlog(
            text="step 4",
            title="makeArgs",
            args=args,
        )
        # 5 generate command line options
        for key, _ in args.items():
            if key in self.parser:
                if self.parser[key]["type"] is None:
                    gen_cmd += self.parser[key]["option_strings"][0] + " "
                else:
                    if key != "InFolder":
                        gen_cmd += self.parser[key]["option_strings"][0] + " " + str(args[key]) + " "
                    else:
                        gen_cmd += self.parser[key]["option_strings"][0] + " " + str(args[key]) + sep + " "
        self.args = args
        self.gen_cmd = gen_cmd
        nlog(
            text="step 4",
            title="makeArgs",
            args=args,
            gen_cms=gen_cmd,
        )

    def slot_restoreDefaults(self):
        if not self.first_start_dialog:
            self.first_start_dialog = True
            self.dlg.destroy()
        if not self.first_start_argparse:
            self.first_start_argparse = True
            self.argdlg.destroy()

    def checkMap(self):
        """
        layerComboBox_ignitionPoints <- no need to be AAIGRID
        layerComboBox_ignitionProbMap
        layerComboBox_cbd
        layerComboBox_fuels
        layerComboBox_ccf
        layerComboBox_elevation
        layerComboBox_cbh
        """
        prefix = "layerComboBox_"
        pl = len(prefix)
        for key in filter(lambda key: key[:pl] == prefix, self.dlg.state):
            if layer := self.dlg.state[key]:
                if key[pl:] != "ignitionPoints":
                    ret, val = check_gdal_driver_name(layer, driver_name="AAIGrid")
                    if not ret:
                        nlog(
                            title="Checking Instance",
                            text="Wrong driver for selected layer. Try gdal_translate -of AAIGrid",
                            comboBox=key,
                            layer_name=layer.name(),
                            driver=val,
                            level=2,
                            to_bar=True,
                        )
                        return False
                    if self.W != layer.width():
                        nlog(
                            title="Checking Instance",
                            text="Raster size mismatch",
                            layer_name=layer.name(),
                            layer_width=layer.width(),
                            instance_width=self.W,
                            level=2,
                            to_bar=True,
                        )
                        return False
                    if self.H != layer.height():
                        nlog(
                            title="Checking Instance",
                            text="Raster size mismatch",
                            layer_name=layer.name(),
                            layer_height=layer.height(),
                            instance_height=self.H,
                            level=2,
                            to_bar=True,
                        )
                        return False
                # TODO stop checking CRS
                if layer.crs() == QgsCoordinateReferenceSystem():
                    nlog(
                        title="Checking Instance",
                        text="CRS not set for",
                        layer_name=layer.name(),
                        comboBox=key,
                        level=2,
                        to_bar=True,
                    )
                    return False
                if layer.crs() != self.crs:
                    nlog(
                        title="Checking Instance",
                        text="CRS mismatch",
                        project_crs=self.crs,
                        layer_crs=layer.crs(),
                        comboBox=key,
                        level=2,
                        to_bar=True,
                    )
                    return False
        """ check if ignitionPoints layer has points """
        if self.dlg.state["radioButton_ignitionPoints"]:
            numPoints, msg = checkLayerPoints(self.dlg.state["layerComboBox_ignitionPoints"])
            if numPoints < 1:
                nlog(
                    title="Checking Instance",
                    text=f"Ignition Point problem: {msg}",
                    level=2,
                    to_bar=True,
                )
                return False
        return True

    def updateProject(self):
        self.now = datetime.now()
        self.project = QgsProject().instance()
        layer = self.dlg.state["layerComboBox_fuels"]
        self.crs = layer.crs()
        self.W = layer.width()
        self.H = layer.height()
        self.extent = layer.extent()

    def run_normal(self):
        """run normal simulation"""
        self.dlg.updateState()
        self.updateProject()
        if not self.checkMap():
            return
        self.makeArgs()
        self.writeInstance()
        cmd = self.proc_exe + " " + self.gen_cmd
        nlog(
            title="main dialog",
            text="run",
            cmd=cmd,
            to_bar=True,
        )
        self.simulation_process.start(cmd)

    def run_dev(self):
        """run dev simulation does not get dialog params"""
        if self.first_start_argparse:
            nlog(
                title="Can't run dev mode",
                text="args dialog has never been opened. Try the second blue button",
                level=1,
                to_bar=True,
            )
            return
        if not self.simulation_process.ended:
            if self.simulation_process.state_code in (QProcess.ProcessState.Running, QProcess.ProcessState.Starting):
                nlog(
                    text="Process already running",
                    title="Can't start dev mode",
                    level=1,
                    to_bar=True,
                )
                return

        self.dlg.updateState()
        self.updateProject()
        self.checkMap()
        header, arg_str, gen_args, workdir = self.argdlg.get()
        self.proc_dir = self.argdlg.fileWidget_directory.filePath()
        nlog(
            title="dev run",
            header=header,
            arg_str=arg_str,
            gen_args=gen_args,
            workdir=workdir,
        )

        """ did opened """
        self.args.update(self.argdlg.gen_args)
        """ but didnt mention inFolder """
        if "InFolder" not in self.argdlg.gen_args:
            nlog(title="dev run", text="Fail: InFolder not in argdialog! Run normal instead!", level=Qgis.Critical)
            return
        if not Path(self.args["InFolder"]).is_dir():
            nlog(title="dev run", text="Fail: InFolder does not exists! Run normal instead!", level=Qgis.Critical)
            return
        self.args["InFolder"] = Path(self.args["InFolder"])
        """ but didnt mention outFolder """
        if "OutFolder" not in self.argdlg.gen_args:
            self.args["OutFolder"] = Path(self.args["InFolder"], "results")
            arg_str += " --output-folder " + str(self.args["OutFolder"])
        else:
            self.args["OutFolder"] = Path(self.args["OutFolder"])
        if not self.args["OutFolder"].is_dir():
            self.args["OutFolder"].mkdir()

        cmd = header + " " + arg_str
        nlog(
            title="main dialog",
            text="dev run",
            cmd=cmd,
            to_bar=True,
        )
        self.simulation_process.start(cmd, proc_dir=workdir)

    def after(self):
        """After the simulation, check if then do:
        - if output folder exists, continue, else abort
        - if logfile exists, load ignition points
        - if Grids folder exists load fire scars, evolution or mean
        - if any of the 5 indicators folder exists, load them or mean them
        """
        # out folder not exists stop
        if not self.args["OutFolder"].is_dir():
            nlog(
                title="After Simulation",
                text="Results folder does not exist!",
                OutFolder=self.args["OutFolder"],
                level=2,
                to_bar=True,
            )
            return
        # logFile for: ignition points
        base_layer = self.dlg.state["layerComboBox_fuels"]
        log_file = Path(self.args["OutFolder"], "LogFile.txt")
        if log_file.is_file():
            name = "Ignition_Points"
            self.task[name] = after_logFile(name, self.dlg, self.iface, nlog, log_file, base_layer, self.plugin_dir)
            self.taskManager.addTask(self.task[name])
        else:
            nlog(
                title="After Simulation",
                text="LogFile.txt does not exist!",
                level=2,
                to_bar=True,
            )
        """ Grids """
        self.dlg.destroy_tables()
        if Path(self.args["OutFolder"], "Grids").is_dir():
            nlog(
                title="After Simulation",
                text="ForestGrids found!",
                level=3,
            )
            layerName = "FireScar"
            # assert isinstance(self.extent , QgsRectangle)
            # assert isinstance(self.crs , QgsCoordinateReferenceSystem)
            self.task[layerName] = after_ForestGrid(
                layerName, layerName, self.iface, self.dlg, self.args, self.extent, self.crs, self.plugin_dir
            )
            self.taskManager.addTask(self.task[layerName])
        else:
            nlog(
                title="After Simulation",
                text="ForestGrids not found!",
                level=2,
                to_bar=True,
            )
        """ stats """
        doit = [
            "OutFl" in self.args,
            "OutIntensity" in self.args,
            "OutRos" in self.args,
            "OutCrownConsumption" in self.args and "cros" in self.args,
            "OutCrown" in self.args and "cros" in self.args,
        ]
        dirNames = ["FlameLength", "Intensity", "RateOfSpread", "CrownFractionBurn", "CrownFire"]
        fileNames = ["FL", "Intensity", "ROSFile", "Cfb", "Crown"]
        layerNames = [
            "Flame_Length",
            "Byram_Intensity",
            "Hit_RateOfSpread",
            "CrownFire_FuelConsumptionRatio",
            "CrownFire_Scar",
        ]
        units = ["m", "kW/m", "m/min", "fraction", "bool"]
        """ background tasks """
        # TODO CrownFire is bool but loaded as float32: modify or create proper qgsTask
        for do, dn, fn, ln, un in zip(doit, dirNames, fileNames, layerNames, units):
            if do:
                if Path(self.args["OutFolder"], dn).is_dir():
                    self.task[ln] = after_asciiDir(
                        ln, self.iface, self.dlg, self.args, dn, fn, ln, un, self.extent, self.crs
                    )
                    self.taskManager.addTask(self.task[ln])
                else:
                    nlog(
                        title="After Simulation",
                        text=f"{dn} folder not found!",
                        level=1,
                        to_bar=True,
                    )

        if Path(self.args["OutFolder"], "Messages").is_dir():
            nlog(
                title="After Simulation",
                text="Messages found!",
                level=3,
            )
            if self.dlg.state["checkBox_betweennessCentrality"]:
                nlog(
                    title="After Simulation",
                    text="Launching betweennessCentrality task!",
                )
                name = "betweenness_centrality"
                self.task[name] = after_betweenness_centrality(
                    name,
                    self.iface,
                    self.dlg,
                    self.args,
                    "Messages",
                    "MessagesFile",
                    self.extent,
                    self.crs,
                    self.plugin_dir,
                )
                self.taskManager.addTask(self.task[name])
            if self.dlg.state["checkBox_downstreamProtectionValue"]:
                nlog(
                    title="After Simulation",
                    text="Launching downstreamProtectionValue task!",
                )
                name = "downstreamProtectionValue"
                self.task[name] = after_downstream_protection_value(
                    name,
                    self.iface,
                    self.dlg,
                    self.args,
                    self.plugin_dir,
                    self.dlg.state["layerComboBox_fuels"],
                    self.dlg.state["layerComboBox_pv"],
                )
                self.taskManager.addTask(self.task[name])

    def slot_run_after(self):
        """processes an output folder
        may delete you files! backup first
        input & output folder must be set on the args dialog first
        """
        if self.first_start_argparse:
            nlog(
                title="Run after can't start",
                text="Set the In|OutFolder in the args dialog first!",
                level=1,
                to_bar=True,
            )
            return
        if not self.simulation_process.ended:
            if self.simulation_process.state_code in (QProcess.ProcessState.Running, QProcess.ProcessState.Starting):
                nlog(
                    title="Run after can't start",
                    text="Process already running",
                    level=1,
                    to_bar=True,
                )
                return
        self.dlg.updateState()
        self.updateProject()
        header, arg_str, gen_args, workdir = self.argdlg.get()
        self.proc_dir = self.argdlg.fileWidget_directory.filePath()
        nlog(
            title="Run after starting",
            text="params",
            header=header,
            arg_str=arg_str,
            gen_args=gen_args,
            workdir=workdir,
            level=0,
        )
        self.args.update(self.argdlg.gen_args)
        self.args["OutFolder"] = Path(self.args["OutFolder"])
        self.after()


# exitCode()
ExitStatus = {
    QProcess.NormalExit: "NormalExit",  # 0
    QProcess.CrashExit: "CrashExit",  # 1
}
# state()
ProcessState = {
    QProcess.NotRunning: "NotRunning",  # 0
    QProcess.Starting: "Running",  # 1
    QProcess.Running: "Starting",  # 2
}
# error()
ProcessError = {
    QProcess.FailedToStart: "FailedToStart",  # 0
    QProcess.Crashed: "Crashe d",  # 1
    QProcess.Timedout: "Timedout",  # 2
    QProcess.ReadError: "ReadError",  # 3
    QProcess.WriteError: "WriteError",  # 4
    QProcess.UnknownError: "UnknownError",  # 5
}


class C2FSB(QProcess):
    """fire simulation qprocess calls the c2fsb repo main.py"""

    def __init__(self, parent=None, proc_dir=None, on_finished=None, plainTextEdit=None):
        super().__init__(parent)
        self.setInputChannelMode(QProcess.ForwardedInputChannel)
        self.setProcessChannelMode(QProcess.SeparateChannels)
        self.readyReadStandardOutput.connect(self.read_standard_output)
        self.readyReadStandardError.connect(self.read_standard_error)
        self.stateChanged.connect(self.on_state_changed)
        if proc_dir:
            self.setWorkingDirectory(str(proc_dir))
            self.proc_dir = proc_dir
        else:
            self.proc_dir = None
        self.finished.connect(self.on_finished)
        self.after = on_finished
        self.plainTextEdit = plainTextEdit
        self.started = None
        self.ended = None
        self.state_code = None
        self.error_code = None
        self.exit_code = None
        self.log_stat("init")

    def log_stat(self, msg):
        self.state_code = self.state()
        self.error_code = self.error()
        self.exit_code = self.exitCode()
        nlog(
            title="simulation",
            text="log_stat",
            msg=msg,
            started=self.started,
            ended=self.ended,
            state=ProcessState.get(self.state_code, "!Unknown"),
            error=ProcessError.get(self.error_code, "!Unknown"),
            exit_code=ExitStatus.get(self.exit_code, "!Unknown"),
        )

    def append_message(self, msg):
        self.plainTextEdit.appendPlainText(msg)

    def start(self, cmd, proc_dir=None):
        self.log_stat("start INI")
        if not self.ended:
            if self.state_code in (QProcess.ProcessState.Running, QProcess.ProcessState.Starting):
                nlog(
                    "Can't start simulation, process already running",
                    title="simulation",
                    text="start",
                    level=Qgis.Warning,
                )
                return
        if proc_dir:
            self.setWorkingDirectory(str(proc_dir))
            self.proc_dir = proc_dir
        self.append_message(f"== process working directory {self.proc_dir}")
        self.append_message(f"== process command {cmd}")
        super().start(cmd)
        self.started = True
        self.ended = False
        self.log_stat("start END")

    def terminate(self):
        self.log_stat("terminate")
        if self.state_code != QProcess.ProcessState.NotRunning:
            super().terminate()
            nlog(
                "Terminate signal sent!",
                title="simulation",
                text="terminate",
                level=Qgis.Success,
            )
        else:
            nlog(
                "Can't send terminate signal!",
                title="simulation",
                text="terminate",
                current_state=ProcessState.get(self.state_code, "!Unknown"),
                ended=self.ended,
                level=Qgis.Warning,
            )

    def kill(self):
        self.log_stat("kill")
        if self.state_code != QProcess.ProcessState.NotRunning:
            super().kill()
            nlog(
                "Kill signal sent!",
                title="simulation",
                text="kill",
                level=Qgis.Success,
            )
        else:
            nlog(
                "Can't send kill signal!",
                title="simulation",
                text="kill",
                current_state=ProcessState.get(self.state_code, "!Unknown"),
                ended=self.ended,
                level=Qgis.Warning,
            )

    def on_finished(self):
        self.ended = True
        self.log_stat("on_finished")
        ok = False
        if self.exit_code == QProcess.NormalExit:
            level = Qgis.Success
            msg = ""
            ok = True
        elif self.exit_code == QProcess.CrashExit:
            level = Qgis.Warning
            msg = f', error:{ProcessError.get(self.error_code, "!Unknown")}'
        else:
            level = Qgis.Critical
            msg = f", code:{self.exit_code}"
            msg += f', error:{ProcessError.get(self.error_code, "!Unknown")}'
        nlog(
            title="simulation",
            text="on_finished",
            level=level,
            exit_status=ExitStatus.get(self.exit_code, "!Unknown"),
            msg=msg,
            to_bar=True,
        )
        if ok and self.after:
            self.after()

    def read_standard_output(self):
        data = self.readAllStandardOutput()
        stdout = bytes(data).decode("utf8")
        self.append_message(stdout)

    def read_standard_error(self):
        data = self.readAllStandardError()
        stderr = bytes(data).decode("utf8")
        self.append_message("===! standard error ouput !===\n" + stderr)

    def on_state_changed(self, state):
        msg = ProcessState.get(state, "!Unknown")
        self.append_message(f"== process state changed : {msg}")
        self.log_stat("on_state_changed")
