# -*- coding: utf-8 -*-
#REPLENV: /home/fdo/pyenv/qgis
"""
/***************************************************************************
 fire2amClass
                                 A QGIS plugin
 Simulate a forest fires under different weather and fire model scenarios
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-07
        git sha              : $Format:%H$
        copyright            : (C) 2023 by fdobadvel (gui) & fire2a team
        email                : fire2a@fire2a.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QProcess, QVariant
from qgis.PyQt.QtWidgets import QAction, QDoubleSpinBox, QSpinBox, QCheckBox
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.Qt import Qt
from qgis.core import QgsProject, Qgis, QgsWkbTypes, QgsMapLayerType, QgsVectorLayer, QgsRasterLayer, QgsField, QgsVectorFileWriter, QgsFeature, QgsGeometry, QgsPointXY, QgsRasterBandStats, QgsCoordinateReferenceSystem #, QgsTask ,QgsApplication, QgsMessageLog 
import processing


# Initialize Qt resources from file resources.py
from .img.resources import *
# Import the code for the dialog
from .fire2am_dialog import fire2amClassDialog
from .fire2am_argparse import fire2amClassDialogArgparse
from .fire2am_utils import check, aName, log, get_params, randomDataFrame
from .qgis_utils import check_gdal_driver_name, matchPoints2Raster, matchRasterCellIds2points, array2rasterFloat32, array2rasterInt16, raster2polygon, mergeVectorLayers, rasterRenderInterpolatedPseudoColor
from .ParseInputs2 import Parser2

from pandas import DataFrame, Timestamp, Series, read_csv, concat
from datetime import datetime, timedelta
from shlex import split as shlex_split
from multiprocessing import cpu_count
from argparse import Namespace
from scipy import stats
from shutil import copy
from glob import glob
import numpy as np
import os.path
import re
from pathlib import Path
import sys

# For debugging
#import pdb
#from qgis.PyQt.QtCore import pyqtRemoveInputHook
# These lines allow you to set a breakpoint in the app
#pyqtRemoveInputHook()
#pdb.set_trace()
# This line enters into interactive
#(Pdb) !import code; code.interact(local=dict(globals(), **locals()))

# ?
#import warnings
#warnings.filterwarnings("ignore",message='Warning: QCoreApplication::exec: The event loop is already running')

class fire2amClass:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'fire2amClass_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Fire Simulator Analytics Management')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start_dialog = None
        self.first_start_argparse = None

        # argparse
        self.default_args, self.parser, self.groups = get_params(Parser2)
        self.gen_cmd = ''
        self.args = {}

        # global
        self.project = None
        self.crs = None
        self.extent = None
        self.geopackage = None

        # QProcess
        #self.proc_dir = str(Path(os.path.join( self.plugin_dir, 'C2FSB')))
        self.proc_dir = str(Path(self.plugin_dir)/'C2FSB')
        self.proc_exe = 'python3 main.py'
        self.proc = None
        self.name_state = { QProcess.ProcessState.NotRunning: 'Not running',
                            QProcess.ProcessState.Starting: 'Starting',
                            QProcess.ProcessState.Running: 'Running' }

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('fire2amClass', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/fire2am/img/icon.png'
        self.add_action(
            icon_path,
            text = self.tr(u'%s: setup and run a forest fire simulation...'%aName),
            callback = self.run_Dialog,
            parent = self.iface.mainWindow())
        # dock start
        self.add_action(
            icon_path = ':/plugins/fire2am/img/icon_dev.png',
            text = self.tr(u'%s: all options (very experimental)'%aName),
            callback = self.run_Argparse,
            parent = self.iface.mainWindow(),
            add_to_toolbar = True)
        # dock end

        # will be set False in run()
        self.first_start_dialog = True
        self.first_start_argparse = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Fire Simulator Analytics Management'),
                action)
            self.iface.removeToolBarIcon(action)

    def run_Argparse(self):
        """Run method that performs all the real work"""
        if self.first_start_argparse == True:
            self.first_start_argparse = False
            self.argdlg = fire2amClassDialogArgparse()
        # show the dialog
        self.argdlg.show()
        # Run the dialog event loop
        result = self.argdlg.exec_()
        print('argdlg result',result)
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def first_start_setup(self):
        ''' layers default names '''
        layers_byName = { l.name():l for l in QgsProject.instance().mapLayers().values()}
        for lname,layer in layers_byName.items():
            if re.match( 'model.*asc', lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_fuels.setLayer(layer)
            elif re.match( 'mdt.*asc', lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_elevation.setLayer(layer)
            elif re.match( 'cbh', lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_cbh.setLayer(layer)
            elif re.match( 'cbd', lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_cbd.setLayer(layer)
            elif re.match( 'ccf', lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_ccf.setLayer(layer)
            elif re.match( '^py', lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_ignitionProbMap.setLayer(layer)
                self.dlg.radioButton_ignitionProbMap.setChecked(True)
            elif re.match( '[Ee]levation', lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_elevation.setLayer(layer)
            elif re.match( '[Ff]uel', lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_fuels.setLayer(layer)
            elif re.match( '[Ii]gnition.*[Pp]rob', lname) and layer.type() == QgsMapLayerType.RasterLayer:
                self.dlg.layerComboBox_ignitionProbMap.setLayer(layer)
            elif re.match( '[Ii]gnition.*[Pp]oint', lname) and layer.type() == QgsMapLayerType.VectorLayer and layer.wkbType() == QgsWkbTypes.Point:
                self.dlg.layerComboBox_ignitionPoints.setLayer(layer)
        ''' weather file'''
        if apath := QgsProject.instance().absolutePath():
            wfile = Path( apath, 'Weather.csv')
            if wfile.is_file(): 
                self.dlg.fileWidget_weatherFile.setFilePath( str(wfile))
                self.dlg.radioButton_weatherFile.setChecked(True)
            ''' weather folder '''
            wfolder = Path( apath, 'Weathers')
            if wfolder.is_dir(): 
                self.dlg.fileWidget_weatherFolder.setFilePath( str(wfolder))
                self.dlg.radioButton_weatherFolder.setChecked(True)
            #self.dlg.args['nweathers'] = 0
        ''' default values '''
        self.dlg.spinBox_nthreads.setValue( max(cpu_count() - 1, 1))
        self.dlg.spinBox_nthreads.setMaximum(cpu_count())

    def connect_slots(self):
        ''' main '''
        #self.dlg.tabWidget.currentChanged.connect(self.slot_tabWidget_currentChanged)
        self.dlg.pushButton_restoreDefaults.pressed.connect(self.slot_restoreDefaults)
        self.dlg.pushButton_run.pressed.connect(self.run_All)
        ''' tab landscape '''
        self.dlg.layerComboBox_fuels.layerChanged.connect( self.slot_trySelectRaster)
        self.dlg.layerComboBox_elevation.layerChanged.connect( self.slot_trySelectRaster)
        self.dlg.layerComboBox_cbh.layerChanged.connect( self.slot_trySelectRaster)
        self.dlg.layerComboBox_cbd.layerChanged.connect( self.slot_trySelectRaster)
        self.dlg.layerComboBox_ccf.layerChanged.connect( self.slot_trySelectRaster)
        ''' tab ignitions ''' 
        self.dlg.layerComboBox_ignitionPoints.layerChanged.connect(self.slot_layerComboBox_ignitionPoints_layerChanged)
        self.dlg.layerComboBox_ignitionProbMap.layerChanged.connect( self.slot_trySelectRaster)
        ''' tab weather '''
        self.dlg.fileWidget_weatherFile.fileChanged.connect( self.slot_fileWidget_weatherFile_fileChanged)
        self.dlg.fileWidget_weatherFolder.fileChanged.connect( self.slot_fileWidget_weatherFolder_fileChanged)
        self.dlg.pushButton_windRandomize.pressed.connect( self.slot_windRandomize)
        #self.dlg.radioButton_weatherFile.clicked.connect( self.slot_radioButton_weatherFile_clicked)
        #self.dlg.radioButton_weatherFolder.clicked.connect( self.slot_radioButton_weatherFolder_clicked)
        ''' tab run '''
        self.dlg.pushButton_dev.pressed.connect(self.externalProcess_start_dev)
        self.dlg.pushButton_run.pressed.connect(self.externalProcess_start)
        self.dlg.pushButton_kill.pressed.connect(self.externalProcess_kill)
        self.dlg.pushButton_terminate.pressed.connect(self.externalProcess_terminate)
        self.dlg.pushButton.pressed.connect(self.slot_doit)
        ''' tab tables '''
        ''' tab graphs '''
        #self.dlg.comboBox_plot.currentIndexChanged.connect( self.showPlot)
        self.dlg.comboBox_plot.currentIndexChanged.connect( lambda index: self.dlg.plt.show(index))

    def slot_windRandomize(self):
       WD = np.random.randint(0,359)
       WS = np.random.randint(1,100)
       self.dlg.spinBox_windDirection.setValue(WD)
       self.dlg.spinBox_windSpeed.setValue(WS)

    def showPlot(self, index):
        log('showing!!!', level=4)
        self.dlg.plt.show(index)

    def run_Dialog(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start_dialog == True:
            self.first_start_dialog  = False
            self.dlg = fire2amClassDialog()
            self.dlg.msgBar.pushMessage(aName+' Hello World!','Keep a project with layers open when interacting', duration=-1, level=Qgis.Info)
            self.slot_windRandomize()
            self.dlg.tabWidget.setCurrentIndex(0)
            self.first_start_setup()
            self.connect_slots()

        '''
        if QgsProject.instance().mapLayers() == {}:
            self.iface.messageBar().pushCritical(aName+': No layers found', 'Open a project with layers and try again')
            log('Open a project with layers and restore defaults', pre='No layers found', level=3)
            return

        if self.project != QgsProject().instance():
            old = self.project
            self.project = QgsProject().instance()
            log( 'Old: %s %s New: %s %s'%( old.absoluteFilePath(), old.baseName(),
                                  self.project.absoluteFilePath(), self.project.baseName()), pre='Project Changed!', level=3, msgBar=self.dlg.msgBar)
        '''
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        print('result',result)
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def makeInstance(self):
        '''mkdir directory, TODO from:copy&paste files to:write layers as new files
        '''
        if os.path.isdir( self.args['InFolder']):
            log( 'directory named %s, stopping!'%self.args['InFolder'], pre='Already Exists!', level=3, msgBar=self.dlg.msgBar)
            return
        os.mkdir( self.args['InFolder'])
        log( self.args['InFolder'],pre='Created directory',level=0, msgBar=self.dlg.msgBar)
        '''
        spain look up table'''
        copy( os.path.join( self.plugin_dir, 'spain_lookup_table.csv') , self.args['InFolder'])
        '''
        elevation '''
        copy( self.dlg.state['layerComboBox_elevation'].publicSource() , 
                os.path.join( self.args['InFolder'], 'elevation.asc'))
        log( 'elevation copied', level=0, msgBar=self.dlg.msgBar)
        '''
        fuels'''
        copy( self.dlg.state['layerComboBox_fuels'].publicSource() , 
                os.path.join( self.args['InFolder'], 'fuels.asc'))
        log( 'fuels copied',level=0, msgBar=self.dlg.msgBar)
        ''' 
        cbh cbd ccf'''
        for name in ['cbh', 'cbd', 'ccf']:
            layer = self.dlg.state['layerComboBox_'+name]
            if layer:
                if layer.type() == QgsMapLayerType.RasterLayer:
                    copy( self.dlg.state['layerComboBox_'+name].publicSource() , 
                        os.path.join( self.args['InFolder'], name+'.asc'))
                    log( name+' layer copied', level=0, msgBar=self.dlg.msgBar)
        '''
        weather'''
        if self.dlg.state['radioButton_weatherConstant']:
            ''' read dial and slider to generate Weather.csv '''
            nrows = self.dlg.state['spinBox_windConstLen']
            iname = self.project.baseName()
            if iname == '':
                iname = 'Jaime'
            Instance = [ iname ] *nrows
            FireScenario = [ 2 ] *nrows
            dt = [ (self.now + timedelta(hours=i)).isoformat(timespec='minutes') for i in range(nrows)]
            WD = [ self.dlg.state['spinBox_windDirection'] ] * nrows
            WS = [ self.dlg.state['spinBox_windSpeed'] ] * nrows
            df = DataFrame( np.vstack((Instance,dt,WD,WS,FireScenario )).T, 
                    columns=['Instance','datetime','WD','WS', 'FireScenario'])
            df.to_csv( os.path.join( self.args['InFolder'],'Weather.csv'), header=True, index=False)
            log( 'speed:%s direction:%s'%(WS,WD), pre='Constant Wind', level=4, msgBar=self.dlg.msgBar)
        elif self.dlg.state['radioButton_weatherFile']:
            ''' copy weather file '''
            copy( self.dlg.state['fileWidget_weatherFile'], os.path.join( self.args['InFolder'], 'Weather.csv'))
            log( 'weather file copied', level=0, msgBar=self.dlg.msgBar)
        elif self.dlg.state['radioButton_weatherFolder']:
            ''' copy weather folder '''
            dst = os.path.join( self.args['InFolder'],'Weathers')
            os.mkdir(dst)
            for filename in glob( self.dlg.state['fileWidget_weatherFolder']+os.sep+'Weather[0-9]*.csv'):
                copy( filename, dst)
            log( 'weather folder copied', level=0, msgBar=self.dlg.msgBar)
        ''' 
        ignitions '''
        if self.dlg.state['radioButton_ignitionPoints']:
            ''' match layer points to raster layer coords, write Ignitions.csv with cell id '''
            points = self.dlg.state['layerComboBox_ignitionPoints']
            raster = self.dlg.state['layerComboBox_fuels']
            ''' match '''
            cellIds, _, _ = matchPoints2Raster( raster, points)
            Ncell = [ c+1 for c in cellIds ]
            if not Ncell:
                log( 'for %s into fuel raster (check crs)'%points.name(), pre='No matching point', level=3, msgBar=self.dlg.msgBar)
                return
            data = { 'Year':None, 'Ncell': Ncell }
            df = DataFrame.from_dict( data)
            df.fillna(1, inplace=True)
            df.to_csv( os.path.join( self.args['InFolder'],'Ignitions.csv'), header=True, index=False)
            log( 'written', pre='Ignition points', level=0, msgBar=self.dlg.msgBar)

        elif self.dlg.state['radioButton_ignitionProbMap']:
            ipm_layer = self.dlg.state['layerComboBox_ignitionProbMap']
            copy( ipm_layer.publicSource() , os.path.join(self.args['InFolder'],'py.asc'))
            log( 'ignitionProbMap copied', level=0, msgBar=self.dlg.msgBar)

    def slot_trySelectRaster(self, layer):
        try:
            if not layer:
                return
            name = self.dlg.sender().objectName()
            if not layer.type() == QgsMapLayerType.RasterLayer:
                log( '%s selected layer %s'%(name,layer.name()), pre='Not Raster!', level=2, msgBar=self.dlg.msgBar)
                return
            ret, val = check_gdal_driver_name( layer, driver_name='AAIGrid')
            if not ret:
                log( '%s selected layer %s has %s driver. Translate to AAIGrid!'%(name,layer.name(),val), pre='Not AAIGrid', level=2, msgBar=self.dlg.msgBar)
                return
            log( '%s selected layer %s'%(name,layer.name()), pre='Is AAIGrid raster!' , level=4, msgBar=self.dlg.msgBar)
        except Exception as e:
            log(e, pre='%s selected layer %s Exception'%(name,layer.name()), level=3, msgBar=self.dlg.msgBar)

    def slot_layerComboBox_ignitionPoints_layerChanged(self, layer):
        def warn_reject(msg):
            self.dlg.radioButton_ignitionRandom.setChecked(True)
            log( 'layer '+layer.name(), pre=msg, level=2,msgBar=self.dlg.msgBar)
        try:
            if not layer:
                return
            if not layer.type() == QgsMapLayerType.VectorLayer:
                warn_reject('Not vector!')
                return
            if not layer.wkbType() == QgsWkbTypes.Point:
                warn_reject('Not with Points!')
                return
            pts = [ f.geometry() for f in layer.getFeatures() \
                    if check( f, 'geometry') and \
                       f.geometry().wkbType() == QgsWkbTypes.Point]
            self.dlg.args['num_ignitions'] = pts
            if len(pts) == 0:
                warn_reject('0 points found!')
                return
            log( 'Read from %s layer'%layer.name(), pre='%s points'%len(pts), level=4, msgBar=self.dlg.msgBar)
            self.dlg.radioButton_ignitionPoints.setChecked(True)
        except Exception as e:
            log( e, pre='Ignition Point layer exception!', level=2, msgBar=self.dlg.msgBar)

    def slot_fileWidget_weatherFolder_fileChanged(self, directory):
        def restore():
            self.dlg.fileWidget_weatherFolder.blockSignals(True)
            self.dlg.fileWidget_weatherFolder.setFilePath( self.project.absolutePath())
            self.dlg.fileWidget_weatherFolder.blockSignals(False)
            self.dlg.radioButton_weatherConstant.setChecked(True)
            self.dlg.args['nweathers'] = 0
        try:
            ''' count sequential Weather files '''
            i=1
            while os.path.isfile( os.path.join( directory, 'Weather'+str(i)+'.csv')):
                i+=1
            i-=1
            if i==0: 
                ''' restore '''
                log( 'Weather files must be a consecutive numbered sequence [1..N]', pre='No Weather[1..N].csv files', level=2, msgBar=self.dlg.msgBar)
                restore()
                return
            log(  'Found in %s'%directory, pre='Weathers[1..%s].csv'%i, level=4, msgBar=self.dlg.msgBar)
            self.dlg.radioButton_weatherFolder.setChecked(True)
            self.dlg.state['radioButton_weatherFolder'] = True
            self.dlg.state['fileWidget_weatherFolder'] = directory
            self.dlg.args['nweathers'] = i
        except Exception as e:
            log( e, pre='Weather Folder %s exception'%directory, level=2, msgBar=self.dlg.msgBar)
            restore()

    def slot_fileWidget_weatherFile_fileChanged(self, filepath):
        def restore():
            self.dlg.fileWidget_weatherFile.blockSignals(True)
            self.dlg.fileWidget_weatherFile.setFilePath( self.project.absolutePath())
            self.dlg.fileWidget_weatherFile.blockSignals(False)
            self.dlg.radioButton_weatherConstant.setChecked(True)
        try:
            df = read_csv( filepath)
            if 'WS' not in df.columns or 'WD' not in df.columns or len(df)==0:
                log(  os.path.basename(filepath)+' file does not contain them', pre='Missing WD or WS columns!', level=2, msgBar=self.dlg.msgBar)
                restore()
                return
            log( 'has WD & WS columns, %s hours (rows)'%len(df), pre=os.path.basename(filepath), level=4, msgBar=self.dlg.msgBar)
            self.dlg.radioButton_weatherFile.setChecked(True)
            self.dlg.state['radioButton_weatherFile'] = True
            self.dlg.state['fileWidget_weatherFile'] = filepath
        except Exception as e:
            log( e, pre='Single .csv file %s exception'%filepath, level=2, msgBar=self.dlg.msgBar)
            restore()

    def makeArgs(self):
        ''' 0 empty args
            1 update with dlg values from spinboxes 
                delete extra ui spinboxes helpers
            2 update with ui logic
            2a  weathers
            2b  ignitions
            2c  nsims
            3 delete default args
            4 update with argparse dialog 
                if opened: with true clicked boxes
                set In|OutFolders = Instance+now
            5 generate command line string 
        '''
        # 0
        args = {}
        gen_cmd = ''
        # 1
        args.update( { o.objectName()[o.objectName().index('_')+1:]: o.value() 
            for o in self.dlg.findChildren( (QDoubleSpinBox, QSpinBox), 
                                        options= Qt.FindChildrenRecursively)})
        args.update( { o.objectName()[o.objectName().index('_')+1:]: o.isChecked()
            for o in self.dlg.findChildren( QCheckBox,
                                        options= Qt.FindChildrenRecursively) if o.isChecked()})
        args.pop('windDirection')
        args.pop('windSpeed')
        args.pop('windConstLen')
        # 2a weather logic
        if self.dlg.state['radioButton_weatherFolder']:
            args['WeatherOpt'] = 'random'
        elif self.dlg.state['radioButton_weatherFile'] or \
             self.dlg.state['radioButton_weatherConstant']:
             args['WeatherOpt'] = 'rows'
        # 2b ignition logic
        if self.dlg.state['radioButton_ignitionPoints']:
            args['ignitions'] = True
        else:
            args.pop('IgRadius')
        # 2c nsims logic
        if args['nsims'] == 1:
            args['grids'] = True
        else:
            args['finalGrid'] = True
        log('make args step 2',args, level=0)
        # 2d crow fire logic
        # TODO ? [ 'OutFl', 'OutIntensity', 'OutRos']
        if 'OutCrown' in args.keys() or 'OutCrownConsumption' in args.keys():
            args['cros'] = True
        # 3 discard default value args 
        popkeys = []
        for dkey in self.default_args:
            for akey in args:
                if dkey == akey and self.default_args[dkey] == args[akey]:
                    popkeys += [akey]
        for akey in popkeys: 
            args.pop(akey)
        log('make args step 3',args, level=0)
        # 4 update argparse dialog
        self.now_str = self.now.strftime('%y-%m-%d_%H-%M-%S')
        if self.first_start_argparse:
            ''' never opened '''
            args['InFolder'] = Path( self.project.absolutePath(), 'Instance'+self.now_str)
            args['OutFolder'] = Path( args['InFolder'], 'results')
        else:
            ''' did opened '''
            args.update(self.argdlg.gen_args)
            ''' but didnt mention ioFolder '''
            if 'InFolder' not in self.argdlg.gen_args.keys():
                args['InFolder'] = Path( self.project.absolutePath(), 'Instance'+self.now_str)
            else:
                args['InFolder'] = Path( args['InFolder'])
            if 'OutFolder' not in self.argdlg.gen_args.keys():
                args['OutFolder'] = Path( args['InFolder'], 'results')
            else:
                args['OutFolder'] = Path( args['OutFolder'])
            self.proc_dir = self.argdlg.fileWidget_directory.filePath()
            self.proc_exe = self.argdlg.header
        log('make args step 4',args, level=0)
        # 5 generate command line options
        for key,val in args.items():
            if key in self.parser.keys():
                if self.parser[key]['type'] is None:
                    gen_cmd += self.parser[key]['option_strings'][0] + ' '
                else:
                    if key!='InFolder':
                        gen_cmd += self.parser[key]['option_strings'][0] + ' ' + str(args[key]) + ' '
                    else:
                        gen_cmd += self.parser[key]['option_strings'][0] + ' ' + str(args[key]) + os.sep + ' '
        self.args = args
        self.gen_cmd = gen_cmd 
        log('make args step 5',args, level=0)
        log('make args step 5',gen_cmd, level=0)

    def slot_restoreDefaults(self):
        if not self.first_start_dialog:
            self.first_start_dialog = True
            self.dlg.destroy()
        if not self.first_start_argparse:
            self.first_start_argparse= True
            self.argdlg.destroy()

    def checkMap(self):
        '''
        layerComboBox_ignitionPoints <- no need to be AAIGRID
        layerComboBox_ignitionProbMap
        layerComboBox_cbd
        layerComboBox_fuels
        layerComboBox_ccf
        layerComboBox_elevation
        layerComboBox_cbh
        '''
        prefix = 'layerComboBox_'
        pl = len(prefix)
        for key in filter( lambda key:  key[:pl] == prefix, self.dlg.state):
            if layer := self.dlg.state[key]:
                if key[pl:] != 'ignitionPoints':
                    ret, val = check_gdal_driver_name( layer, driver_name='AAIGrid')
                    if not ret:
                        log( '%s selected layer %s has %s driver. Translate to AAIGrid!'%(key, layer.name(),val), pre='Not AAIGrid', level=2, msgBar=self.dlg.msgBar)
                        return False

                if layer.crs() == QgsCoordinateReferenceSystem():
                    log('has not been set for',layer.name(),'in', key, pre='CRS error', level=3, msgBar=self.dlg.msgBar)
                    return False
                if layer.crs() != self.crs:
                    log(str(layer.crs())+' is different from project '+str(self.crs)+'in'+str(key), pre='CRS error', level=3, msgBar=self.dlg.msgBar)
                    return False
        return True

    def checkSameRasterExtentAndResolution(self):
        ''' TODO
        '''
        for i,li in enumerate(lyrs):
            for j,lj in enumerate(lyrs):
                if i<j:
                    self.externalProcess_message(str(lyrs[li][0].extent().asWktCoordinates()))
                    self.externalProcess_message(str(lyrs[li][0].extent().asWktCoordinates()))
                    self.externalProcess_message(str(lyrs[lj][0].extent().asWktCoordinates()))
                    self.externalProcess_message( str(lyrs[li][0].extent().contains( lyrs[lj][0].extent())))
                    if not (lyrs[li][0].extent().contains( lyrs[lj][0].extent()) and \
                            lyrs[lj][0].extent().contains( lyrs[li][0].extent()) ):
                        log('have different extents!',lyrs[li][0].name(), lyrs[lj][0].name(), pre='CRS!', level=3, msgBar=self.dlg.msgBar)
                        self.externalProcess_message(str(lyrs[li][0].extent()))
                        self.externalProcess_message(str(lyrs[lj][0].extent()))
                        return False
        return True

    def updateProject(self):
        self.now = datetime.now()
        self.project = QgsProject().instance()
        self.crs = self.project.crs()
        self.extent = self.dlg.state['layerComboBox_fuels'].extent()

    def run_All(self):
        self.dlg.updateState()
        self.updateProject()
        if not self.checkMap():
            return
        self.makeArgs()
        self.geopackage = os.path.join( self.args['OutFolder'], 'outputs.gpkg')
        self.makeInstance()
        self.externalProcess_start()

    def externalProcess_message(self, s):
        self.dlg.plainTextEdit.appendPlainText(s)

    def externalProcess_kill(self):
        if self.proc:
            self.externalProcess_message('Killing run process with state: '+self.name_state[self.proc.state()])
            self.proc.kill()
            return
        log('Nothing to kill', pre='Run process', level=1, msgBar=self.dlg.msgBar)

    def externalProcess_terminate(self):
        if self.proc:
            self.externalProcess_message('Terminating run process with state: '+self.name_state[self.proc.state()])
            self.proc.terminate()
            return
        log('Nothing to terminate', pre='Run process', level=1, msgBar=self.dlg.msgBar)

    def externalProcess_start(self):
        if self.proc is None:
            self.externalProcess_message('Starting run process '+self.gen_cmd)
            log('Starting run process '+self.gen_cmd,level=0)

            self.proc = QProcess()
            self.proc.setInputChannelMode(QProcess.ForwardedInputChannel)
            self.proc.setProcessChannelMode( QProcess.SeparateChannels)
            self.proc.readyReadStandardOutput.connect(self.externalProcess_handle_stdout)
            self.proc.readyReadStandardError.connect(self.externalProcess_handle_stderr)
            self.proc.stateChanged.connect(self.externalProcess_handle_state)
            self.proc.finished.connect(self.externalProcess_finished)  # Clean up once complete.
            self.proc.setWorkingDirectory( self.proc_dir)
            self.externalProcess_message('workdir %s'%self.proc_dir)
            ar = shlex_split( self.proc_exe +' '+ self.gen_cmd , posix="win" not in sys.platform )
            self.externalProcess_message('args %s'%ar)
            log( 'ar', *ar, level=0)
            self.proc.start( ar[0], ar[1:] )
            self.externalProcess_message('Started')
            log('Started',level=0)
            '''basic
            self.proc.setWorkingDirectory( os.path.join( self.plugin_dir, 'extras'))
            self.proc.start("python3", ['dummy_proc.py'])
            '''

    def externalProcess_start_dev(self):
        if self.first_start_argparse:
            log('dev dialog has never been opened (not created)', pre="Can't run dev mode", level=2)
            return
        if self.proc:
            log('Process is running', pre="Can't run dev mode", level=2)
            return

        self.dlg.updateState()
        self.updateProject()
        self.checkMap()
        header, arg_str, gen_args, workdir = self.argdlg.get()
        self.args['OutFolder'] = gen_args['OutFolder']
        self.geopackage = os.path.join( self.args['OutFolder'], 'outputs.gpkg')

        self.proc = QProcess()
        self.proc.setInputChannelMode( QProcess.ForwardedInputChannel)
        self.proc.setProcessChannelMode( QProcess.SeparateChannels)
        self.proc.readyReadStandardOutput.connect( self.externalProcess_handle_stdout)
        self.proc.readyReadStandardError.connect( self.externalProcess_handle_stderr)
        self.proc.stateChanged.connect( self.externalProcess_handle_state)
        self.proc.finished.connect( self.externalProcess_finished)

        log('Starting DEV run'+arg_str,level=0)
        self.proc.setWorkingDirectory( workdir)
        ar = shlex_split( header + ' ' + arg_str )
        self.proc.start( ar[0], ar[1:] )
        self.externalProcess_message('Started DEV run:\n\t%s\n\t%s'%(workdir,ar))

    def externalProcess_handle_stderr(self):
        data = self.proc.readAllStandardError()
        stderr = bytes(data).decode("utf8")
        self.externalProcess_message('!@#$%^&* stdError stream:\n'+stderr)

    def externalProcess_handle_stdout(self):
        data = self.proc.readAllStandardOutput()
        stdout = bytes(data).decode("utf8")
        self.externalProcess_message(stdout)

    def externalProcess_handle_state(self, state):
        self.externalProcess_message('State changed: '+self.name_state[state])

    def externalProcess_finished(self):
        self.externalProcess_message("Process finished.")
        self.proc = None
        if not os.path.isdir( self.args['OutFolder'] ):
            log('results folder',self.args['OutFolder'], pre='Does NOT exist', msgBar=self.dlg.msgBar, level=3)
            return
        if os.path.isfile( os.path.join(self.args['OutFolder'], 'LogFile.txt')):
            log('Loading results started...', pre='Success!', level=4, msgBar=self.dlg.msgBar)
            self.loadResults()
        else:
            log('LogFile.txt not available', pre='No Results', level=3, msgBar=self.dlg.msgBar)

    def loadResults(self):
        ''' read LogFile.txt 
            generate ignition point(s) layer
            if nsim = 1 : isochrones
            else : heatmap
        '''
        ''' print LogFile.txt '''
        logfile = os.path.join(self.args['OutFolder'], 'LogFile.txt')
        with open(logfile, 'rb', buffering=0) as afile:
            text = afile.read().decode()
            self.externalProcess_message( text)


        ''' add output layer GROUP : 
            MOVING LAYERS AND ADDING TO GROUPS IS BUGGY 
            outputGroupName='OUTPUT_'+os.path.basename(os.path.normpath(self.args['OutFolder']))
            root = QgsProject.instance().layerTreeRoot()
            outputGroup = root.addGroup(outputGroupName)
            fireEvGroup = outputGroup.addGroup('Fire Evolution')
            gridGroup = fireEvGroup.addGroup('Grids')
            polyGroup = fireEvGroup.addGroup('Polygons')
             TODO handle removing older/other output groups
            group = root.findGroup(groupName)
            if not group:
                group = root.addGroup(groupName)
        '''
        ''' how many sims were ran '''
        if 'nsims' in self.args.keys():
            nsims = self.args['nsims']
        else:
            nsims = self.default_args['nsims']
        if nsims == 1:
            self.load1sim()
        else:
            self.loadsims()

        self.after_ignitionPoints( text)

        doit = [ 'OutFl' in self.args.keys(),
                 'OutIntensity' in self.args.keys(),
                 'OutRos' in self.args.keys(),
                 'OutCrownConsumption' in self.args.keys()]
        directories = ['FlameLength', 'Intensity', 'RateOfSpread', 'CrownFractionBurn']
        filenames = ['FL', 'Intensity', 'ROSFile', 'Cfb']
        names = ['flame_length', 'Byram_intensity', 'hit_ROS', 'crown_fire_fuel_consumption_ratio']
        if nsims > 1:
            names = ['mean_'+n for n in names ]

        for i,(d,f,n) in filter( lambda x: doit[x[0]] , enumerate(zip(directories, filenames, names))):
            self.after_asciiDir2float32MeanRaster(d, f, n, self.args['OutFolder'], self.geopackage, self.extent, self.crs, nodata=0.0)

        if 'OutCrown' in self.args.keys():
            layerName = 'crown_fire_scar'
            if nsims > 1:
                layerName = 'mean_'+layerName
            self.after_asciiDir2Int16MeanRaster( 'CrownFire', 'Crown', layerName, self.args['OutFolder'], self.geopackage, self.extent, self.crs, nodata=0.0)

    def after_ignitionPoints(self, text):
        data = np.fromiter( re.findall( 'ignition point for Year [0-9]*, sim ([0-9]+): ([0-9]+)', text), dtype=np.dtype((int,2)) )
        simulation, ignitionCell = data.T
        feats = []
        for s,(x,y) in zip(simulation, matchRasterCellIds2points( ignitionCell-1, self.dlg.state['layerComboBox_fuels'])):
            f = QgsFeature()
            f.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(x,y)))
            f.setId(s)
            feats += [ f]
        layerName = 'ignition points'
        vectorLayer = QgsVectorLayer( 'point', layerName, 'memory')
        vectorLayer.setCrs( self.crs)
        ret, val = vectorLayer.dataProvider().addFeatures(feats)
        log( ret, val, layerName, pre = 'vectorLayer data provider added features', level=0)
        options = QgsVectorFileWriter.SaveVectorOptions()
        options.driverName = 'GPKG'
        options.layerName = layerName
        if os.path.exists(self.geopackage):
            options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer
        else:
            options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
        ret, val = QgsVectorFileWriter.writeAsVectorFormat( vectorLayer , self.geopackage, options)
        log( ret, val, layerName, pre = 'vectorLayer writeAsVectorFormat', level=1)
        vectorLayer = self.iface.addVectorLayer( self.geopackage+'|layername='+layerName, layerName, 'ogr')
        vectorLayer.loadNamedStyle( os.path.join( self.plugin_dir, 'img'+os.sep+'points_layerStyle.qml'))
        log('finished loading results', pre='Done!', level=4, msgBar=self.dlg.msgBar)

    def after_asciiDir2Int16MeanRaster(self, dirName, fileName, layerName, outfolder, geopackage, extent, crs, nodata = None):
        ''' get filelist '''
        filelist = sorted( Path( outfolder, dirName).glob(fileName+'[0-9]*.asc'))
        filestring = ' '.join([ f.stem for f in filelist ])
        nsim = np.fromiter( re.findall( '([0-9]+)', filestring), dtype=int, count=len(filelist))
        asort = np.argsort( nsim)
        nsim = nsim[ asort]
        filelist = np.array( filelist)[ asort]
        widthNum = len(str(np.max( nsim)))
        ''' get all asc 2 array '''
        self.externalProcess_message('Getting '+layerName+' grids to arrays...')
        data = []
        for afile in filelist:
            data += [ np.loadtxt( afile,  dtype=bool, skiprows=6)]
        data = np.array(data)
        '''global stats'''
        self.externalProcess_message(layerName+' global statistics '+str(stats.describe(data, axis=None)))
        ''' calc mean '''
        self.externalProcess_message('Calculating '+layerName+'...')
        array2rasterFloat32( np.mean( data, axis=0, dtype=np.float32), layerName, self.geopackage, extent, crs, nodata = 0.0)
        ''' show layer '''
        layer = self.iface.addRasterLayer('GPKG:'+self.geopackage+':'+layerName, layerName)
        minValue = layer.dataProvider().bandStatistics(1, QgsRasterBandStats.Min).minimumValue
        maxValue = layer.dataProvider().bandStatistics(1, QgsRasterBandStats.Max).maximumValue
        rasterRenderInterpolatedPseudoColor(layer, minValue, maxValue)

    def after_asciiDir2float32MeanRaster(self, dirName, fileName, layerName, outfolder, geopackage, extent, crs, nodata = None):
        '''
            dirName = 'FlameLength'
            fileName ='FL'
            layerName ='mean_flame_length'
            outfolder = self.args['OutFolder']
            geopackage= os.path.join(self.args['OutFolder'], 'outputs.gpkg')
            extent = None,
            crs = self.project.crs,
            nodata = 0.0 ):
            ['CrownFire'      ] ['FlameLength'      , 'Intensity'           , 'RateOfSpread']
            ['Crown'          ] ['FL'               , 'Intensity'           , 'ROSFile'     ]
            ['mean_crown_fire'] ['mean_flame_length', 'mean_Byram_intensity', 'mean_hit_ROS']
            import os.path
            from glob import glob
            import numpy as np
            import re
            outfolder = '/home/fdo/dev/Zona21/Instance23-03-14_15-49-22/results'
            filelist = glob( outfolder+os.sep+'FlameLength'+os.sep+'FL[0-9]*.asc')
            nsim = np.fromiter( re.findall( 'FlameLength'+os.sep+'FL([0-9]+).asc', ' '.join(filelist)), dtype=int)
            array2rasterFloat32( np.mean( data, axis=0), 'mean_flame_length', self.geopackage, extent, crs, nodata = 0.0)
        '''
        ''' get filelist '''
        filelist = sorted( Path( outfolder, dirName).glob(fileName+'[0-9]*.asc'))
        filestring = ' '.join([ f.stem for f in filelist ])
        nsim = np.fromiter( re.findall( '([0-9]+)', filestring), dtype=int, count=len(filelist))
        asort = np.argsort( nsim)
        nsim = nsim[ asort]
        filelist = np.array( filelist)[ asort]
        widthNum = len(str(np.max( nsim)))
        ''' get all asc 2 array '''
        self.externalProcess_message('Getting '+layerName+' grids to arrays...')
        data = []
        for afile in filelist:
            data += [ np.loadtxt( afile,  dtype=np.float32, skiprows=6)]
        data = np.array(data)
        '''global stats'''
        self.externalProcess_message(layerName+' global statistics '+str(stats.describe(data, axis=None)))
        ''' calc mean '''
        self.externalProcess_message('Calculating '+layerName+'...')
        array2rasterFloat32( np.mean( data, axis=0, dtype=np.float32), layerName, self.geopackage, extent, crs, nodata = 0.0)
        ''' show layer '''
        layer = self.iface.addRasterLayer('GPKG:'+self.geopackage+':'+layerName, layerName)
        minValue = layer.dataProvider().bandStatistics(1, QgsRasterBandStats.Min).minimumValue
        maxValue = layer.dataProvider().bandStatistics(1, QgsRasterBandStats.Max).maximumValue
        rasterRenderInterpolatedPseudoColor(layer, minValue, maxValue)

    def loadsims(self):
        extent = self.dlg.state['layerComboBox_fuels'].extent()
        crs = self.project.crs()
        outfolder = self.args['OutFolder']

        ''' get ordered file list '''
        # debug filelist = sorted( Path.cwd().joinpath('Grids').glob('Grids[0-9]*'+os.sep+'ForestGrid[0-9]*.csv'))
        filelist = sorted( Path( outfolder, 'Grids').glob('Grids[0-9]*'+os.sep+'ForestGrid[0-9]*.csv'))
        filestring = ' '.join([ f'{f.parts[-2]}_{f.parts[-1]}' for f in filelist ])
        numbers = np.fromiter( re.findall( 'Grids([0-9]+)_ForestGrid([0-9]+).csv', filestring), dtype=np.dtype((int,2)), count=len(filelist))
        # get the last forest_grid for each grid_folder
        doindex = np.unique( numbers[::-1][:,0], return_index=True)[1]
        filelist = np.array(filelist)[::-1][doindex]
        numbers = numbers[::-1][doindex]
        first, second = numbers.T
        width1stNum, width2ndNum = len(str(np.max(first))), len(str(np.max(second)))

        ''' get all csv 2 array '''
        self.externalProcess_message('Getting csv grids to arrays...')
        data = []
        for afile in filelist:
            data += [ np.loadtxt( afile , delimiter=',', dtype=np.int8)]
        data = np.array(data)

        ''' calc burnprob '''
        self.externalProcess_message('Calculating burn probabilities...')
        array2rasterFloat32( np.mean( data, axis=0), 'mean_prob_burn', self.geopackage, extent, crs, nodata = 0.0)
        self.externalProcess_message('Added mean_prob_burn raster')
        array2rasterFloat32(  np.std( data, axis=0),  'std_prob_burn', self.geopackage, extent, crs, nodata = 0.0)
        self.externalProcess_message('Added std_prob_burn raster')
        self.externalProcess_message('Burn probabilities global statistics'+str(stats.describe(data, axis=None)))
        layer = self.iface.addRasterLayer('GPKG:'+self.geopackage+':mean_prob_burn', 'mean_prob_burn')

        minValue = layer.dataProvider().bandStatistics(1, QgsRasterBandStats.Min).minimumValue
        maxValue = layer.dataProvider().bandStatistics(1, QgsRasterBandStats.Max).maximumValue
        rasterRenderInterpolatedPseudoColor(layer, minValue, maxValue)

        ''' calc fire scars'''
        self.externalProcess_message('Making fire scar rasters...')
        for i,(nsim,ngrid) in enumerate(numbers):
            layerName = 'rFireScar_'+str(nsim).zfill(width1stNum)+'_'+str(ngrid).zfill(width2ndNum)
            array2rasterInt16( data[i], layerName, self.geopackage, extent, crs, nodata = 0)
        self.externalProcess_message('All done!...')
        log('Simulations loaded correctly',pre='All done!', level=4, msgBar=self.dlg.msgBar)

    def load1sim(self):
        extent = self.dlg.state['layerComboBox_fuels'].extent()
        crs = self.project.crs()
        outfolder = self.args['OutFolder']

        ''' get ordered file list '''
        filelist = sorted( Path( outfolder, 'Grids').glob('Grids[0-9]*'+os.sep+'ForestGrid[0-9]*.csv'))
        filestring = ' '.join([ f'{f.parts[-2]}_{f.parts[-1]}' for f in filelist ])
        numbers = np.fromiter( re.findall( 'Grids([0-9]+)_ForestGrid([0-9]+).csv', filestring), dtype=np.dtype((int,2)))
        first, second = numbers.T
        width1stNum, width2ndNum = len(str(np.max(first))), len(str(np.max(second)))

        ''' get all csv 2 array '''
        self.externalProcess_message('Getting csv grids to arrays...')
        data = []
        for afile in filelist:
            data += [ np.loadtxt( afile , delimiter=',', dtype=np.int8)]
        data = np.array(data)

        ''' calc fire evo raster '''
        self.externalProcess_message('Making fire evolution rasters...')
        for i,(nsim,ngrid) in enumerate(numbers):
            layerName = 'rFireEvolution_'+str(nsim).zfill(width1stNum)+'_'+str(ngrid).zfill(width2ndNum)
            array2rasterInt16( data[i], layerName, self.geopackage, extent, crs, nodata = 0)
            #raster = array2rasterLayerInt16( data[i], layerName, self.geopackage, extent, crs, nodata = 0)
            #poly = raster2poly( raster, layerName, extent, crs)
        ''' raster 2 poly 
            1 get weather for datetime tagging
        '''

        self.externalProcess_message('Making fire evolution polygons...')
        weather_folder = self.args['OutFolder'] / 'WeatherHistory'
        weather_hist_file = weather_folder / 'WeatherHistory.csv'
        ok = False
        if weather_folder.is_dir() and weather_hist_file.is_file():
            with open( weather_hist_file, 'r') as afile:
                if weather_file := afile.readline():
                    weather_file = Path(weather_file[:-1]) #erase last char \n
                    if weather_file.is_file():
                        ok = True
        if not ok:
            weather_file = Path( self.args['InFolder'], 'Weather.csv')

        if weather_file.is_file():
            ds = read_csv( weather_file).datetime
            log('Weather.csv.datetime found with length',len(ds), level=1)
            while len(ds) < len(numbers):
                nextdt = Timestamp(ds.iloc[-1]) + timedelta(hours=1)
                nextidx= ds.index[-1] + 1
                ds = concat(( ds, Series( nextdt, index=[nextidx])))
        else:
            log('Weather.csv in input instance folder', pre='Does NOT exist', msgBar=self.dlg.msgBar, level=3)
            plop = self.now - timedelta(years=1)
            ds = Series( [ plop + timedelta(hours=i) for i in range(len(numbers)) ],
                           index=range(len(numbers)) )
        ds = ds.apply( lambda x: Timestamp(x).isoformat(timespec='seconds'))
        log('adjusted Weather.csv.datetime length',len(ds), level=1)
        ''' 2 load raster, make poly, add datetime fields, write '''
        options = QgsVectorFileWriter.SaveVectorOptions()
        options.driverName = 'GPKG'
        for i,(nsim,ngrid) in enumerate(numbers):
            layerName = 'FireEvolution_'+str(nsim).zfill(width1stNum)+'_'+str(ngrid).zfill(width2ndNum)
            rasterLayer = QgsRasterLayer('GPKG:'+self.geopackage+':r'+layerName, 'r'+layerName)
            tmp = processing.run('gdal:polygonize',
                       {'BAND' : 1, 
                        'EIGHT_CONNECTEDNESS' : False, 
                        'EXTRA' : '', 
                        'FIELD' : 'DN', 
                        'INPUT' : rasterLayer, 
                        'OUTPUT' : 'TEMPORARY_OUTPUT' })['OUTPUT']
            vectorLayer = QgsVectorLayer( tmp, 'v'+layerName)
            options.layerName = 'v'+layerName
            # add datetime field
            if not vectorLayer.isEditable():
                vectorLayer.startEditing()
            vectorLayer.dataProvider().addAttributes([QgsField('datetime',QVariant.DateTime)])
            vectorLayer.updateFields()
            id_dt = vectorLayer.fields().indexFromName('datetime')
            for feature in vectorLayer.getFeatures():
                attr = { id_dt : ds.iloc[i]}
                vectorLayer.dataProvider().changeAttributeValues({ feature.id() : attr})
            vectorLayer.commitChanges()
            # write
            if os.path.exists(self.geopackage):
                options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer
            else:
                options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
            QgsVectorFileWriter.writeAsVectorFormat( vectorLayer, self.geopackage, options)
            del rasterLayer, vectorLayer
        ''' merge '''
        self.externalProcess_message('Merging fire evolution polygons...')
        polys=[]
        for i,(nsim,ngrid) in enumerate(numbers):
            layerName = 'vFireEvolution_'+str(nsim).zfill(width1stNum)+'_'+str(ngrid).zfill(width2ndNum)
            polys += [ self.geopackage+'|layername='+layerName ]
        mergedName = 'merged_Fire_Evolution'
        mergeVectorLayers( polys, self.geopackage, mergedName )
        vectorLayer = self.iface.addVectorLayer( self.geopackage+'|layername='+mergedName, mergedName, 'ogr')
        vectorLayer.loadNamedStyle( os.path.join( self.plugin_dir, 'img'+os.sep+mergedName+'_layerStyle.qml'))

    def slot_doit(self):
        self.iface.messageBar().pushSuccess(aName+': do it', 'push button pressed')
