name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'fire2am.zip'
        exclusions: '*.git*'

